- name: "Configure local workstation"
  hosts: localhost
  gather_facts: true
  roles:
    - role: packages
      tags: ['packages']
    - role: asdf
      tags: ['asdf']
    - role: zsh
      tags: ['zsh']