- name: "Configure local workstation"
  hosts: localhost
  gather_facts: true
  roles:
    - role: packages
      tags: ['packages']
    - role: asdf
      tags: ['asdf']
    - role: zsh
      tags: ['zsh']
    - role: node
      tags: ['node']
    - role: krew
      tags: ['krew']
    - role: ollama
      tags: ['ollama']
