- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
  
- name: Get a list of installed packages from brew cask
  command: /usr/local/bin/brew list --casks
  register: brew_casks
  changed_when: false

- name: Get a list of installed packages from brew formula
  command: /usr/local/bin/brew list --formula
  register: brew_formula
  changed_when: false         

- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    update_homebrew: yes
  ignore_errors: yes
  when: "'{{ item }}' not in brew_casks.stdout"
  with_items:
    - google-drive
    - docker
    - google-chrome
    - google-cloud-sdk
    - iterm2
    - slack
    - sublime-text
    - telegram
    - visual-studio-code
    - vlc
    - zoom
    - bitwarden
    - virtualbox
    - clickup
    - notion
    - google-cloud-sdk
    - lens
    - stats
    - docker
    - spotify
    - whatsapp
    - microsoft-teams
    - microsoft-office
    - balenaetcher
    - audacity


- name: "Install formula packages via brew"
  community.general.homebrew:
    name: "{{ item }}"
  ignore_errors: yes
  when: "'{{ item }}' not in brew_formula.stdout"
  with_items:
    - aws-iam-authenticator
    - awscli
    - coreutils
    - curl
    - gpg
    - htop
    - kubectx
    - kubernetes-cli
    - libtool
    - libxslt
    - libyaml
    - openssl
    - tmux
    - unixodbc
    - unzip
    - vim
    - xz
    - zsh
    - k9s
    - stern
    - thefuck
    - jq
    - yq
    - helm
    - mas
    - pre-commit
    - languagetool

- name: Install a list of apps from mac store
  community.general.mas:
    id:
       - 472790630 # olive tree bible
       - 497799835 # xcode
       - 408981434 # imovie
    state: present


- name: Upgrade all installed Mac App Store apps
  community.general.mas:
    upgrade_all: true



 