- name: "Install homebrew"
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew

- name: "Make sure homebrew bin is in path"
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: "Get installed cask packages"
  ansible.builtin.command: /opt/homebrew/bin/brew list --casks
  register: brew_casks
  changed_when: false

- name: "Get installed formula packages"
  ansible.builtin.command: /opt/homebrew/bin/brew list --formula
  register: brew_formula
  changed_when: false

- name: "Install core packages via brew casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
    update_homebrew: true
  failed_when: false
  when: "item not in brew_casks.stdout"
  with_items:
    - google-drive
    - docker
    - google-chrome
    - google-cloud-sdk
    - iterm2
    - slack
    - sublime-text
    - telegram
    - vlc
    - zoom
    - bitwarden
    - virtualbox
    - notion
    - notion-calendar
    - stats
    - docker
    - spotify
    - whatsapp
    - the-unarchiver
    - keybase
    - warp
    - cursor
    - pritunl
    - dbeaver-community

- name: "Install formula packages via brew"
  community.general.homebrew:
    name: "{{ item }}"
  failed_when: false
  when: "item not in brew_formula.stdout"
  with_items:
    - aws-iam-authenticator
    - awscli
    - coreutils
    - curl
    - gpg
    - htop
    - kubectx
    - kubernetes-cli
    - libtool
    - libxslt
    - libyaml
    - openssl
    - tmux
    - unixodbc
    - unzip
    - vim
    - xz
    - zsh
    - k9s
    - stern
    - thefuck
    - jq
    - yq
    - helm
    - mas
    - pre-commit
    - languagetool
    - oci-cli
    - gnupg
    - sops
    - htop
    - sops

- name: "Install apps from mac store"
  community.general.mas:
    id:
      - 472790630 # olive tree bible
      - 497799835 # xcode
      - 408981434 # imovie
      - 6447783111 # Sider: Ask AI Chat Bot, Writer
    state: present