- git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/Users/{{ lookup('env', 'USER') }}/.asdf"
    version: v0.11.3
- name: "Create a default asdf configuration"
  template:
    src: templates/.asdfrc.j2
    dest: /Users/{{ lookup('env', 'USER') }}/.asdfrc
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Add commands to ~/.zshrc
  blockinfile:
    dest: ~/.zshrc
    block: |
      #set history size
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash


- name: "Install asdf plugins"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - terragrunt
    - terraform
    - golang
    - kind

- name: "Install Default Terraform"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install terraform 1.4.6
    asdf global terraform 1.4.6

- name: "Install Default Terragrunt"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install terragrunt 0.45.0
    asdf global terragrunt 0.45.0

- name: "Install Default Golang"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install golang 1.20
    asdf global golang 1.20

- name: "Install Default Kind"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install kind latest
    asdf global kind latest