- name: "Clone ASDF repository"
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/Users/{{ lookup('env', 'USER') }}/.asdf"
    version: v0.11.3

- name: "Create a default asdf configuration"
  ansible.builtin.template:
    src: templates/.asdfrc.j2
    dest: "/Users/{{ lookup('env', 'USER') }}/.asdfrc"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0644'
    force: true

- name: "Install asdf plugins"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - terragrunt
    - terraform
    - golang
    - kind
    - nodejs
  changed_when: false

- name: "Install Default Terraform"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install terraform 1.6.1
    asdf global terraform 1.6.1
  changed_when: false

- name: "Install Default Terragrunt"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install terragrunt 0.45.0
    asdf global terragrunt 0.45.0
  changed_when: false

- name: "Install Default Golang"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install golang 1.20
    asdf global golang 1.20
  changed_when: false

- name: "Install Default Kind"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install kind latest
    asdf global kind latest
  changed_when: false

- name: "Install Default Nodejs"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install nodejs 20.10.0
    asdf global nodejs 20.10.0
  changed_when: false
