- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

- name: Set ZSH as the default shell
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: True

- name: Fix permissions for zsh (if needed)
  file:
    name: "{{ item }}"
    mode: g-w,o-w
  loop:
    - /usr/local/share/zsh/site-functions
    - /usr/local/share/zsh
    
- name: Chnage ~/.zshrc
  replace:
    dest: ~/.zshrc
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    mode: u=rw,g=r,o=r
  loop:
    - regexp: '^plugins=.*'
      replace: plugins=(colored-man-pages dirhistory docker git history vagrant-prompt kubectl)


- name: Add commands to ~/.zshrc
  blockinfile:
    dest: ~/.zshrc
    block: |
      #set history size
      export HISTSIZE=50000
      #save history after logout
      export SAVEHIST=10000
      #save only one command if 2 common are same and consistent
      setopt HIST_IGNORE_ALL_DUPS
      #add timestamp for each entry
      setopt EXTENDED_HISTORY
      # Do not share history between sessions (like bash)
      setopt NO_SHARE_HISTORY
      # Remove the quarantine flag when it installs a package
      export HOMEBREW_CASK_OPTS="--no-quarantine"
      # Use bat for the brew cat command
      export HOMEBREW_BAT=1
      # Cleanup all cached files older than this many days
      export HOMEBREW_CLEANUP_MAX_AGE_DAYS=7
      # Fail on the failure of installation from a bottle rather than falling back to building from source
      export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

      alias dos2unix="sed -i 's/\r$//' "
      alias unix2dos="awk 'sub(\"$\",\"\r\")' "
      alias md5sum_dir="rhash --md5 --recursive --percents --output=md5sum.md5 ."
      alias k=kubectl
      alias history="history -i"
      trash() { mv -fv "$@" ~/.Trash/ ; }

      DISABLE_AUTO_UPDATE="true"
      COMPLETION_WAITING_DOTS="true"
      HIST_STAMPS="yyyy-mm-dd"

      # Always reply Yes and automatically upgrade oh-my-zsh
      DISABLE_UPDATE_PROMPT=true
      
      # export ASDF
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
      
