- name: "Install global npm packages"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    npm install -g {{ item }}
  changed_when: false
  with_items:
    - pnpm
    - yarn

- name: "Configure pnpm"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    pnpm setup
  changed_when: false

- name: "Source pnpm environment"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.zshrc
  changed_when: false

- name: "Install packages using pnpm"
  ansible.builtin.shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    source /Users/{{ lookup('env', 'USER') }}/.zshrc
    pnpm add -g {{ item }}
  changed_when: false
  with_items:
    - cdktf-cli@0.20.11
    - cdk@2.177.0